Make API level and scheduling group count configurable
zpp-2022-rust-seastar/seastar-rs pull request #7
Opened 2023-01-04 18:09 UTC by patjed41

Code added in this PR sets `SEASTAR_API_LEVEL` and `SEASTAR_SCHEDULING_GROUPS_COUNT` the way pkg_config would. Moreover, all other -D variables are also defined. It turned out to be really easy to implement. It's just a simple iteration over the elements of `seastar.defines`.

I also added `.cpp_link_stdlib("stdc++")` that will be necessary later.

2023-01-05 15:26 UTC, Lorak-mmk requested changes
Left one comment, otherwise it's good to go.

2023-01-05 15:26 UTC, Lorak-mmk commented on seastar/build.rs
> +            Some(val) => build.define(var, &val[..]),
`&val[..]` -> `val.as_str()`

2023-01-05 16:04 UTC, patjed41 commented on seastar/build.rs
> +            Some(val) => build.define(var, &val[..]),
Done.

2023-01-06 08:06 UTC, Lorak-mmk approved these changes

2023-01-06 10:35 UTC, merged